# Generated by Django 5.0.1 on 2024-03-03 20:04

import event.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_users_managers_users_last_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', event.models.CustomUserManager()),
            ],
        ),
    ]
